module.exports = 
  RDIO_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXX'
  RDIO_SECRET: 'XXXXXXXXXX'
  RDIO_USERNAME: 'XXXXXXXXXXXXX'

  DBOX_APP_KEY: 'XXXXXXXXXXXXXXX'
  DBOX_APP_SECRET: 'XXXXXXXXXXXXXXX'
  DBOX_ACCESS_TOKEN: 'XXXXXXXXXXXXXXX'
  DBOX_ACCESS_SECRET: 'XXXXXXXXXXXXXXX'

