module.exports =
  DBOX_APP_KEY: 'XXXXXXXXXXXXXXX'
  DBOX_APP_SECRET: 'XXXXXXXXXXXXXXX'
  DBOX_ACCESS_TOKEN: 'XXXXXXXXXXXXXXX'
  DBOX_ACCESS_SECRET: 'XXXXXXXXXXXXXXX'

  GITHUB_USERNAME: 'XXXXXXXX'

  MOUNTAIN_PROJECT_ID: 'XXXXXXXXX'
