module.exports =
  RDIO_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXX'
  RDIO_SECRET: 'XXXXXXXXXX'
  RDIO_USERNAME: 'XXXXXXXXXXXXX'
  RDIO_ACCESS_TOKEN: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  RDIO_ACCESS_SECRET: 'XXXXXXXXXXXX'

  DBOX_APP_KEY: 'XXXXXXXXXXXXXXX'
  DBOX_APP_SECRET: 'XXXXXXXXXXXXXXX'
  DBOX_ACCESS_TOKEN: 'XXXXXXXXXXXXXXX'
  DBOX_ACCESS_SECRET: 'XXXXXXXXXXXXXXX'

  GITHUB_USERNAME: 'XXXXXXXX'

